# CSV must include a 'URL' column with a full href
csvURL: https://docs.google.com/spreadsheets/d/1YAMUyk16E1vY3Pbz1kpHe5f18Xk1JyLGhd_4FpCg63M/pub?output=csv

# add '(Y/N)' to the field name to return an 'if exists' Boolean
fields:
    name (Y/N)': '//dl/dd[2]/dl/dt[1]'
    strasse (Y/N)': '//dl/dd[4]/p/text()[2]'

output: scraped.csv
